"use strict";
const agentList = [
    { id: 0, engName: "yuzuha", korName: "유즈하", image: "yuzuha", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 3000 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: true, amount: 171 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 1, engName: "jufufu", korName: "귤복복", image: "jufufu", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 3400 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 50 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 2, engName: "yixuan", korName: "의현", image: "yixuan", ability: [
            { "HP": "", valid: true, amount: 18000 },
            { "공격력": "", valid: false, amount: 0 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 68 },
            { "치명타 피해": "", valid: true, amount: 130 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관입력": "", valid: true, amount: 2300 },
            { "기운 자동 누적": "", valid: false, amount: 0 }
        ] },
    { id: 3, engName: "hugo", korName: "휴고 블라드", image: "hugo", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2700 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 88 },
            { "치명타 피해": "", valid: true, amount: 120 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 4, engName: "vivian", korName: "비비안 밴시", image: "vivian", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2100 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: true, amount: 390 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 5, engName: "trigger", korName: "트리거", image: "trigger", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2000 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: true, amount: 160 },
            { "치명타 확률": "", valid: true, amount: 78 },
            { "치명타 피해": "", valid: true, amount: 100 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 6, engName: "0-anby", korName: "0호-앤비", image: "0-anby", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 3200 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 78 },
            { "치명타 피해": "", valid: true, amount: 140 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 7, engName: "evelyn", korName: "이블린 슈발리에", image: "evelyn", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2800 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 75 },
            { "치명타 피해": "", valid: true, amount: 150 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 8, engName: "astra", korName: "아스트라 야오", image: "astra", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 3429 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 9, engName: "harumasa", korName: "아사바 하루마사", image: "harumasa", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 3000 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 75 },
            { "치명타 피해": "", valid: true, amount: 140 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 10, engName: "miyabi", korName: "호시미 미야비", image: "miyabi", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2500 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 87 },
            { "치명타 피해": "", valid: true, amount: 120 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 11, engName: "lighter", korName: "라이터", image: "lighter", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: false, amount: 0 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 50 },
            { "치명타 피해": "", valid: true, amount: 100 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 12, engName: "yanagi", korName: "츠키시로 야나기", image: "yanagi", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2600 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: true, amount: 375 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 13, engName: "burnice", korName: "버니스 화이트", image: "burnice", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2800 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: true, amount: 300 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 14, engName: "caesar", korName: "카이사르 킹", image: "caesar", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2000 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: true, amount: 300 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 15, engName: "jane", korName: "제인 도", image: "jane", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2400 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: false, amount: 0 },
            { "치명타 피해": "", valid: false, amount: 0 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: true, amount: 420 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 16, engName: "qingyi", korName: "청의", image: "qingyi", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: false, amount: 0 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 50 },
            { "치명타 피해": "", valid: true, amount: 100 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 17, engName: "zhuyuan", korName: "주연", image: "zhuyuan", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2800 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 35 },
            { "치명타 피해": "", valid: true, amount: 200 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] },
    { id: 18, engName: "ellenjoe", korName: "엘렌 조", image: "ellenjoe", ability: [
            { "HP": "", valid: false, amount: 0 },
            { "공격력": "", valid: true, amount: 2800 },
            { "방어력": "", valid: false, amount: 0 },
            { "충격력": "", valid: false, amount: 0 },
            { "치명타 확률": "", valid: true, amount: 75 },
            { "치명타 피해": "", valid: true, amount: 140 },
            { "이상 장악력": "", valid: false, amount: 0 },
            { "이상 마스터리": "", valid: false, amount: 0 },
            { "관통률": "", valid: false, amount: 0 },
            { "에너지 자동 회복": "", valid: false, amount: 0 }
        ] }
];
